# Generated by Django 2.2.4 on 2020-09-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='related_user',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='TX', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.CharField(max_length=255),
        ),
    ]
