# Generated by Django 2.2.4 on 2020-09-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200922_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='related_user',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to='profile_image'),
        ),
    ]
